/**
 * Phase 10: Solve Jobs API client with resilient polling, cancellation, and ETag management.
 * Follows Blueprint Section 28 & 31: modest scoped polling with cancellation/backoff; no gratuitous WebSockets.
 */
import { SolveJobCreateRequest, SolveJobResponse, SolveJobListResponse, PlanVersion } from '../types/api';

const API_BASE = '/api/v1/planning';

export interface SubmitJobOptions {
  idempotencyKey?: string;
}

export interface PollJobOptions {
  initialDelayMs?: number;
  maxDelayMs?: number;
  backoffFactor?: number;
  timeoutMs?: number;
  onPhaseChange?: (job: SolveJobResponse) => void;
  signal?: AbortSignal;
}

export class SolveJobApi {
  /**
   * Submits a solve job to the backend queue.
   * Returns HTTP 202 Accepted with job representation and ETag.
   */
  static async submitJob(
    request: SolveJobCreateRequest,
    options?: SubmitJobOptions
  ): Promise<{ job: SolveJobResponse; etag: string; isNew: boolean }> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (options?.idempotencyKey) {
      headers['Idempotency-Key'] = options.idempotencyKey;
    }

    const response = await fetch(`${API_BASE}/solve-jobs`, {
      method: 'POST',
      headers,
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      const err = await response.json().catch(() => ({ detail: response.statusText }));
      throw new Error(err.detail || `Job submission failed with status ${response.status}`);
    }

    const etag = response.headers.get('ETag') || '';
    const job: SolveJobResponse = await response.json();
    const isNew = response.status === 202;

    return { job, etag, isNew };
  }

  /**
   * Retrieves the current status of a solve job.
   */
  static async getJob(jobId: string, signal?: AbortSignal): Promise<{ job: SolveJobResponse; etag: string }> {
    const response = await fetch(`${API_BASE}/solve-jobs/${jobId}`, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
      },
      signal,
    });

    if (!response.ok) {
      const err = await response.json().catch(() => ({ detail: response.statusText }));
      throw new Error(err.detail || `Failed to fetch job '${jobId}' (${response.status})`);
    }

    const etag = response.headers.get('ETag') || '';
    const job: SolveJobResponse = await response.json();
    return { job, etag };
  }

  /**
   * Lists solve jobs with optional corridor filter.
   */
  static async listJobs(corridorCode?: string, status?: string): Promise<SolveJobListResponse> {
    const params = new URLSearchParams();
    if (corridorCode) params.append('corridor_code', corridorCode);
    if (status) params.append('status', status);

    const response = await fetch(`${API_BASE}/solve-jobs?${params.toString()}`);
    if (!response.ok) {
      throw new Error(`Failed to list jobs (${response.status})`);
    }
    return response.json();
  }

  /**
   * Cancels a queued or running job with optimistic concurrency check.
   */
  static async cancelJob(
    jobId: string,
    reason: string = 'User requested cancellation',
    etag?: string
  ): Promise<SolveJobResponse> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (etag) {
      headers['If-Match'] = etag;
    }

    const response = await fetch(`${API_BASE}/solve-jobs/${jobId}/cancel`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ reason }),
    });

    if (!response.ok) {
      const err = await response.json().catch(() => ({ detail: response.statusText }));
      throw new Error(err.detail || `Failed to cancel job (${response.status})`);
    }

    return response.json();
  }

  /**
   * Retrieves the finalized plan version generated by a completed job.
   */
  static async getPlan(planId: string): Promise<PlanVersion> {
    const response = await fetch(`${API_BASE}/plans/${planId}`);
    if (!response.ok) {
      throw new Error(`Failed to fetch plan '${planId}' (${response.status})`);
    }
    return response.json();
  }

  /**
   * Lists all saved plan versions for the corridor.
   */
  static async listPlans(corridorCode?: string): Promise<PlanVersion[]> {
    const params = new URLSearchParams();
    if (corridorCode) params.append('corridor_code', corridorCode);
    const response = await fetch(`${API_BASE}/plans?${params.toString()}`);
    if (!response.ok) {
      throw new Error(`Failed to list plans (${response.status})`);
    }
    return response.json();
  }

  /**
   * Triggers asynchronous leased worker execution for a queued job.
   */
  static async executeJob(jobId: string): Promise<{ status: string; job_id: string }> {
    const response = await fetch(`${API_BASE}/solve-jobs/${jobId}/execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
    });
    if (!response.ok) {
      throw new Error(`Failed to dispatch worker for job '${jobId}' (${response.status})`);
    }
    return response.json();
  }

  /**
   * Fetches the spatial corridor topology (stations, chainage km, track segments).
   */
  static async getTopology(corridorCode: string = 'VKC'): Promise<any> {
    const response = await fetch(`${API_BASE}/corridor/topology?corridor_code=${corridorCode}`);
    if (!response.ok) {
      throw new Error(`Failed to fetch topology (${response.status})`);
    }
    return response.json();
  }

  /**
   * Fetches the Working Timetable train occupations for the corridor.
   */
  static async getOccupations(corridorCode: string = 'VKC'): Promise<any[]> {
    const response = await fetch(`${API_BASE}/timetable/occupations?corridor_code=${corridorCode}`);
    if (!response.ok) {
      throw new Error(`Failed to fetch occupations (${response.status})`);
    }
    return response.json();
  }

  /**
   * Solves a tactical 30-day monthly plan allocation across 4 calendar weeks.
   */
  static async allocateMonthlyPlan(request: any): Promise<any> {
    const response = await fetch(`${API_BASE}/monthly/allocate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(request),
    });
    if (!response.ok) {
      const err = await response.json().catch(() => ({ detail: response.statusText }));
      throw new Error(err.detail || `Monthly allocation failed (${response.status})`);
    }
    return response.json();
  }

  /**
   * Lists stored tactical monthly allocation plans.
   */
  static async listMonthlyPlans(corridorCode?: string): Promise<any[]> {
    const params = new URLSearchParams();
    if (corridorCode) params.append('corridor_code', corridorCode);
    const response = await fetch(`${API_BASE}/monthly/plans?${params.toString()}`);
    if (!response.ok) {
      throw new Error(`Failed to list monthly plans (${response.status})`);
    }
    return response.json();
  }

  /**
   * Lists two-horizon reconciliation cases.
   */
  static async getReconciliationCases(parentPlanId?: string, childPlanId?: string): Promise<any[]> {
    const params = new URLSearchParams();
    if (parentPlanId) params.append('parent_plan_id', parentPlanId);
    if (childPlanId) params.append('child_plan_id', childPlanId);
    const response = await fetch(`${API_BASE}/reconciliation/cases?${params.toString()}`);
    if (!response.ok) {
      throw new Error(`Failed to list reconciliation cases (${response.status})`);
    }
    return response.json();
  }

  /**
   * Polls a job until terminal state (COMPLETED, FAILED, CANCELLED) with exponential backoff and jitter.
   */
  static async pollJobUntilTerminal(
    jobId: string,
    options?: PollJobOptions
  ): Promise<SolveJobResponse> {
    const initialDelay = options?.initialDelayMs ?? 1500;
    const maxDelay = options?.maxDelayMs ?? 5000;
    const factor = options?.backoffFactor ?? 1.4;
    const timeout = options?.timeoutMs ?? 120000; // 2 minutes max
    const startTime = Date.now();

    let delay = initialDelay;
    let lastPhase = '';

    while (true) {
      if (Date.now() - startTime > timeout) {
        throw new Error(`Polling timed out after ${timeout}ms for job '${jobId}'.`);
      }

      if (options?.signal?.aborted) {
        throw new Error(`Polling aborted for job '${jobId}'.`);
      }

      const { job } = await SolveJobApi.getJob(jobId, options?.signal);

      if (job.current_phase !== lastPhase) {
        lastPhase = job.current_phase;
        options?.onPhaseChange?.(job);
      }

      if (job.status === 'COMPLETED' || job.status === 'FAILED' || job.status === 'CANCELLED') {
        return job;
      }

      // Exponential backoff with 10% jitter
      const jitter = (Math.random() - 0.5) * 0.2 * delay;
      const sleepTime = Math.min(maxDelay, delay + jitter);
      await new Promise((resolve) => setTimeout(resolve, sleepTime));
      delay = Math.min(maxDelay, delay * factor);
    }
  }
}
