"""
Common models, base configurations, and standard RFC 7807 error schema.
"""
from typing import Any, Dict, List, Optional
from datetime import datetime, timezone
from pydantic import BaseModel, ConfigDict, Field


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class APIModel(BaseModel):
    """Base model enforcing strict types and explicit validation."""
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        extra="forbid",
    )


class InvalidParam(APIModel):
    name: str = Field(..., description="Field path that failed validation")
    reason: str = Field(..., description="Human-readable explanation of rejection")


class ProblemDetails(APIModel):
    """RFC 7807 Problem Details specification representation."""
    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type"
    )
    title: str = Field(..., description="A short, human-readable summary of the problem type")
    status: int = Field(..., description="The HTTP status code generated by the origin server")
    detail: str = Field(..., description="A human-readable explanation specific to this occurrence")
    instance: Optional[str] = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence of the problem"
    )
    error_code: str = Field(..., description="Machine-readable application error code")
    invalid_params: Optional[List[InvalidParam]] = Field(
        default=None,
        description="List of invalid request parameters if applicable"
    )
    timestamp: datetime = Field(
        default_factory=utc_now,
        description="UTC timestamp when the error occurred"
    )


class DatabaseHealth(APIModel):
    connected: bool
    engine: str
    latency_ms: Optional[float] = None
    error: Optional[str] = None


class HealthResponse(APIModel):
    status: str = Field(..., description="'healthy' or 'degraded'")
    app_name: str = "SAMARATH"
    version: str = "0.1.0"
    process: str = "reachable"
    database: DatabaseHealth
    timestamp_utc: datetime = Field(default_factory=utc_now)
